name: Test
on:
  push
jobs:
  test-sentry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.10
      - name: install dependencies
        run: poetry install
      - name: Run tests again
        run: poetry run pytest
